sonar.projectKey=vviderski_planner-zw
sonar.organization=vviderski
sonar.projectName=Planner ZW
sonar.projectVersion=1.0

sonar.sources=src,api
sonar.tests=
sonar.exclusions=node_modules/**,dist/**,public/**,*.sql,*.config.js,postcss.config.js,tailwind.config.js,vite.config.js
sonar.sourceEncoding=UTF-8
